<?php

namespace ContainerZ0jzAzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_57sUEwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5_7sUEw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5_7sUEw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'annonce' => ['privates', '.errored..service_locator.5_7sUEw.App\\Entity\\Annonces', NULL, 'Cannot autowire service ".service_locator.5_7sUEw": it needs an instance of "App\\Entity\\Annonces" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'annonce' => 'App\\Entity\\Annonces',
            'entityManager' => '?',
        ]);
    }
}
