<?php

namespace ContainerUoJxrn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__HgQvBvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..hgQvBv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..hgQvBv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AnnoncesAllController::delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesAllController::edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesAllController::index' => ['privates', '.service_locator.dvK8oDp', 'get_ServiceLocator_DvK8oDpService', true],
            'App\\Controller\\AnnoncesAllController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnoncesAllController::show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\AnnoncesClientController::delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesClientController::edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesClientController::index' => ['privates', '.service_locator.3xAHgD.', 'get_ServiceLocator_3xAHgD_Service', true],
            'App\\Controller\\AnnoncesClientController::new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\AnnoncesClientController::show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\AnnoncesController::delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesController::edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesController::index' => ['privates', '.service_locator.dvK8oDp', 'get_ServiceLocator_DvK8oDpService', true],
            'App\\Controller\\AnnoncesController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnoncesController::show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\CategoriesController::delete' => ['privates', '.service_locator.8IzX0f9', 'get_ServiceLocator_8IzX0f9Service', true],
            'App\\Controller\\CategoriesController::edit' => ['privates', '.service_locator.8IzX0f9', 'get_ServiceLocator_8IzX0f9Service', true],
            'App\\Controller\\CategoriesController::index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\CategoriesController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoriesController::show' => ['privates', '.service_locator.i60bMqk', 'get_ServiceLocator_I60bMqkService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AnnoncesAllController:delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesAllController:edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesAllController:index' => ['privates', '.service_locator.dvK8oDp', 'get_ServiceLocator_DvK8oDpService', true],
            'App\\Controller\\AnnoncesAllController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnoncesAllController:show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\AnnoncesClientController:delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesClientController:edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesClientController:index' => ['privates', '.service_locator.3xAHgD.', 'get_ServiceLocator_3xAHgD_Service', true],
            'App\\Controller\\AnnoncesClientController:new' => ['privates', '.service_locator.AUQz.CV', 'get_ServiceLocator_AUQz_CVService', true],
            'App\\Controller\\AnnoncesClientController:show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\AnnoncesController:delete' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesController:edit' => ['privates', '.service_locator.5_7sUEw', 'get_ServiceLocator_57sUEwService', true],
            'App\\Controller\\AnnoncesController:index' => ['privates', '.service_locator.dvK8oDp', 'get_ServiceLocator_DvK8oDpService', true],
            'App\\Controller\\AnnoncesController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnnoncesController:show' => ['privates', '.service_locator.xNNyuFf', 'get_ServiceLocator_XNNyuFfService', true],
            'App\\Controller\\CategoriesController:delete' => ['privates', '.service_locator.8IzX0f9', 'get_ServiceLocator_8IzX0f9Service', true],
            'App\\Controller\\CategoriesController:edit' => ['privates', '.service_locator.8IzX0f9', 'get_ServiceLocator_8IzX0f9Service', true],
            'App\\Controller\\CategoriesController:index' => ['privates', '.service_locator.do9sDn8', 'get_ServiceLocator_Do9sDn8Service', true],
            'App\\Controller\\CategoriesController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategoriesController:show' => ['privates', '.service_locator.i60bMqk', 'get_ServiceLocator_I60bMqkService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.UUMJOv4', 'get_ServiceLocator_UUMJOv4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AnnoncesAllController::delete' => '?',
            'App\\Controller\\AnnoncesAllController::edit' => '?',
            'App\\Controller\\AnnoncesAllController::index' => '?',
            'App\\Controller\\AnnoncesAllController::new' => '?',
            'App\\Controller\\AnnoncesAllController::show' => '?',
            'App\\Controller\\AnnoncesClientController::delete' => '?',
            'App\\Controller\\AnnoncesClientController::edit' => '?',
            'App\\Controller\\AnnoncesClientController::index' => '?',
            'App\\Controller\\AnnoncesClientController::new' => '?',
            'App\\Controller\\AnnoncesClientController::show' => '?',
            'App\\Controller\\AnnoncesController::delete' => '?',
            'App\\Controller\\AnnoncesController::edit' => '?',
            'App\\Controller\\AnnoncesController::index' => '?',
            'App\\Controller\\AnnoncesController::new' => '?',
            'App\\Controller\\AnnoncesController::show' => '?',
            'App\\Controller\\CategoriesController::delete' => '?',
            'App\\Controller\\CategoriesController::edit' => '?',
            'App\\Controller\\CategoriesController::index' => '?',
            'App\\Controller\\CategoriesController::new' => '?',
            'App\\Controller\\CategoriesController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnnoncesAllController:delete' => '?',
            'App\\Controller\\AnnoncesAllController:edit' => '?',
            'App\\Controller\\AnnoncesAllController:index' => '?',
            'App\\Controller\\AnnoncesAllController:new' => '?',
            'App\\Controller\\AnnoncesAllController:show' => '?',
            'App\\Controller\\AnnoncesClientController:delete' => '?',
            'App\\Controller\\AnnoncesClientController:edit' => '?',
            'App\\Controller\\AnnoncesClientController:index' => '?',
            'App\\Controller\\AnnoncesClientController:new' => '?',
            'App\\Controller\\AnnoncesClientController:show' => '?',
            'App\\Controller\\AnnoncesController:delete' => '?',
            'App\\Controller\\AnnoncesController:edit' => '?',
            'App\\Controller\\AnnoncesController:index' => '?',
            'App\\Controller\\AnnoncesController:new' => '?',
            'App\\Controller\\AnnoncesController:show' => '?',
            'App\\Controller\\CategoriesController:delete' => '?',
            'App\\Controller\\CategoriesController:edit' => '?',
            'App\\Controller\\CategoriesController:index' => '?',
            'App\\Controller\\CategoriesController:new' => '?',
            'App\\Controller\\CategoriesController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
