<?php

namespace ContainerUoJxrn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonces2TypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Annonces2Type' shared autowired service.
     *
     * @return \App\Form\Annonces2Type
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Annonces2Type.php';

        return $container->privates['App\\Form\\Annonces2Type'] = new \App\Form\Annonces2Type();
    }
}
