<?php

namespace ContainerUoJxrn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnoncesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5_7sUEw.App\Entity\Annonces' shared service.
     *
     * @return \App\Entity\Annonces
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5_7sUEw": it needs an instance of "App\\Entity\\Annonces" but this type has been excluded in "config/services.yaml".');
    }
}
