<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoJxrn1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoJxrn1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoJxrn1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoJxrn1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUoJxrn1\App_KernelDevDebugContainer([
    'container.build_hash' => 'UoJxrn1',
    'container.build_id' => '78e49ff8',
    'container.build_time' => 1700131946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoJxrn1');
